Perbaikan pertama tidak menemukan konteks tepat; saya lihat baris terkait lalu menerapkan patch yang lebih presisi.
Action: view_file({"path":"/app/frontend/src/App.js","view_range":[1,12]})
Observation: [Showing lines 1-12 of 21 total] /app/frontend/src/App.js:
1|import { useEffect, useMemo, useState } from "react";
2|import axios from "axios";
3|import { CalendarDays, Camera, Check, ChevronDown, ClipboardList, Download, FileText, LayoutDashboard, LogOut, MapPin, Menu, Plus, ShieldCheck, Users, X, Clock3 } from "lucide-react";
4|import "@/App.css";
5|
6|const API = `${process.env.REACT_APP_BACKEND_URL}/api`;
7|const DEMOS = [{label:"Admin / Kepala Sekolah",id:"admin@smadigital.id",password:"admin123",role:"admin"},{label:"Guru",id:"198706122014031002",password:"guru123",role:"guru"},{label:"Staff TU",id:"staff@smadigital.id",password:"staff123",role:"staff"},{label:"Siswa",id:"20240017",password:"siswa123",role:"siswa"}];
8|const nav = [{id:"overview",label:"Ringkasan",icon:LayoutDashboard},{id:"attendance",label:"Presensi",icon:Clock3},{id:"requests",label:"Pengajuan",icon:ClipboardList},{id:"users",label:"Pengguna",icon:Users}];
9|const demoRows=[{name:"Arka Wijaya",role:"Siswa",class_name:"XI IPA 2",check_in:"06:47",check_out:"15:22",status:"Hadir"},{name:"Bima Santoso",role:"Guru",class_name:"-",check_in:"07:18",check_out:"15:46",status:"Terlambat"},{name:"Siti Rahma",role:"Siswa",class_name:"X IPA 1",check_in:"06:52",check_out:"15:10",status:"Hadir"},{name:"Dewi Lestari",role:"Staff",class_name:"-",check_in:"07:02",check_out:"15:05",status:"Hadir"},{name:"Fajar Nugroho",role:"Siswa",class_name:"XII IPS 2",check_in:"-",check_out:"-",status:"Izin"}];
10|function apiError(e){return e?.response?.data?.detail || "Terjadi kendala. Coba lagi."}
11|function Login({onLogin}){const [identifier,setIdentifier]=useState("admin@smadigital.id"),[password,setPassword]=useState("admin123"),[error,setError]=useState(""); const submit=async e=>{e.preventDefault();try{const r=await axios.post(`${API}/auth/login`,{identifier,password});onLogin(r.data)}catch(err){setError(apiError(err))}};return <main className="login-shell"><div className="login-image"><div className="image-overlay"/><div className="login-quote"><span className="eyebrow">SMA DIGITAL NUSANTARA</span><h1>Hadir untuk<br/><em>masa depan.</em></h1><p>Kelola kehadiran sekolah dengan lebih tertib, transparan, dan bermakna.</p><div className="quote-rule"/><small>Presensi Sekolah Nusantara · 2025</small></div></div><section className="login-panel"><div className="brand-mark"><ShieldCheck size={22}/><span>presensi<span>.</span></span></div><div className="login-form"><span className="eyebrow blue">PORTAL SEKOLAH</span><h2>Selamat datang kembali</h2><p className="muted">Masuk untuk melanjutkan ke ruang kerja Anda.</p><form onSubmit={submit}><label>ID Pengguna<input data-testid="login-identifier-input" value={identifier} onChange={e=>setIdentifier(e.target.value)} placeholder="NIS, NIP, atau email"/></label><label>Password<input data-testid="login-password-input" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Masukkan password"/></label>{error&&<div className="error" data-testid="login-error">{error}</div>}<button className="primary-btn" data-testid="login-submit-button">Masuk ke portal <span>→</span></button></form><div className="demo-label">AKUN DEMO CEPAT</div><div className="demo-grid">{DEMOS.map(d=><button data-testid={`demo-${d.role}-button`} key={d.role} onClick={()=>{setIdentifier(d.id);setPassword(d.password)}}><b>{d.label}</b><small>{d.id}</small></button>)}</div></div><small className="login-footer">© 2025 SMA Digital Nusantara · Sistem Presensi Terpadu</small></section></main>}
12|function Shell({user,section,setSection,onLogout,children}){return <div className="app-shell"><aside className="sidebar"><div className="brand-mark side"><ShieldCheck size={21}/><span>presensi<span>.</span></span></div><div className="school-name"><b>SMA DIGITAL</b><small>NUSANTARA</small></div><nav>{nav.filter(x=>user.role==="siswa"?x.id!=="users":true).map(n=>{const I=n.icon;return <button data-testid={`nav-${n.id}-button`} className={section===n.id?"active":""} onClick={()=>setSection(n.id)} key={n.id}><I size={18}/>{n.label}</button>})}</nav><div className="sidebar-bottom"><div className="secure"><ShieldCheck size={17}/><span><b>Data terlindungi</b><small>Sinkron terakhir 2 mnt lalu</small></span></div><button className="logout" data-testid="logout-button" onClick={onLogout}><LogOut size={17}/>Keluar</button></div></aside><main className="main-content"><header><button className="mobile-menu" data-testid="mobile-menu-button"><Menu/></button><div><span className="eyebrow blue">SELASA, 18 FEBRUARI 2025</span><h1>{section==="overview"?"Selamat pagi, ":section==="attendance"?"Presensi":""}{section==="overview"&&<em>{user.name.split(" ")[0]}.</em>}</h1></div><div className="header-user"><div className="avatar">{user.avatar}</div><div><b>{user.name}</b><small>{user.role_label}</small></div><ChevronDown size={16}/></div></header>{children}</main></div>}
 [12 lines shown. Remaining: lines 13-21 (9 lines). Use view_range parameter to continue.]
